name: example
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  equatable: 1.2.6
  meta: 1.2.4
  graphql: ^4.0.1
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  graphql_to_dart:
    path: ../
