name: graphql_to_dart
description: A simple dart package to generate complete Dart models from a GraphQL endpoint by leveraging GraphQL introspection API.
version: 1.1.0
homepage: https://github.com/vikram25897/graphql_to_dart
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  yaml: ^3.1.0
  graphql: 5.0.0-nullsafety.4
  gql: ^0.13.0-nullsafety.2
  build: ^2.0.1
  source_gen: ^1.0.0
  recase: ^4.0.0
  code_builder: ^4.0.0
