name: graphql_to_dart
description: A simple dart package to generate complete Dart models from a GraphQL endpoint by leveraging GraphQL introspection API.
version: 1.1.0
homepage: https://github.com/vikram25897/graphql_to_dart
environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  yaml: ^2.2.1
  graphql: ^4.0.1
  gql: ^0.12.4
  gql_code_gen: ^0.1.5
  build: 1.6.2
  source_gen: 0.9.10+3
  recase: ^3.0.0

