const Map<String, List<String>> events = {
  "generic": [
    'Started',
    'Excuted',
    'IsLoading',
    'IsOptimistic',
    'IsConcrete',
    'Errored',
    'Failed',
    'Reseted',
    'Refreshed',
   
  ],
  "createOne": [
     'Started',
    'Excuted',
    'IsLoading',
    'IsOptimistic',
    'IsConcrete',
    'Errored',
    'Failed',
    'Reseted',
    'Refreshed',
  ],
  "createMany": [
     'Started',
    'Excuted',
    'IsLoading',
    'IsOptimistic',
    'IsConcrete',
    'Errored',
    'Failed',
    'Reseted',
    'Refreshed',
  ],
  "updateOne": [
    'Started',
    'Excuted',
    'IsLoading',
    'IsOptimistic',
    'IsConcrete',
    'Errored',
    'Failed',
    'Reseted',
    'Refreshed'
  ],
  "updateMany": [
     'Started',
    'Excuted',
    'IsLoading',
    'IsOptimistic',
    'IsConcrete',
    'Errored',
    'Failed',
    'Reseted',
    'Refreshed',
  ],
  "deleteOne": [
    'Started',
    'Excuted',
    'IsLoading',
    'IsOptimistic',
    'IsConcrete',
    'Errored',
    'Failed',
    'Reseted',
    'Refreshed',
  ],
  "deleteMany": [
    'Started',
    'Excuted',
    'IsLoading',
    'IsOptimistic',
    'IsConcrete',
    'Errored',
    'Failed',
    'Reseted',
    'Refreshed',
  ],
  "findUnique": [
    'Started',
    'Excuted',
    'IsLoading',
    'IsOptimistic',
    'IsConcrete',
    'Errored',
    'Failed',
    'Reseted',
    'Refreshed',
  ],
  "findMany": [
     'Started',
    'Excuted',
    'IsLoading',
    'IsOptimistic',
    'IsConcrete',
    'Errored',
    'Failed',
    'Reseted',
    'Refreshed',
    'MoreLoaded',
    'StreamEnded'
  ],
  "findFirst": [
    'Started',
    'Excuted',
    'IsLoading',
    'IsOptimistic',
    'IsConcrete',
    'Errored',
    'Failed',
    'Reseted',
    'Refreshed',
    'MoreLoaded',
    'StreamEnded'
  ],
};