const keywords = {
  "int":true,
  "double":true,
  "String":true,
  "Map":true,
  "Set":true,
  "bool":true,
  "abstract": true,
  "else": true,
  "import": true,
  "super": true,
  "as": true,
  "enum": true,
  "in": true,
  "switch": true,
  "assert": true,
  "export": true,
  "interface": true,
  "sync": true,
  "async": true,
  "extends": true,
  "is": true,
  "this": true,
  "await": true,
  "extension": true,
  "library": true,
  "throw": true,
  "break": true,
  "external": true,
  "mixin": true,
  "true": true,
  "case": true,
  "factory": true,
  "new": true,
  "try": true,
  "catch": true,
  "false": true,
  "null": true,
  "typedef": true,
  "class": true,
  "final": true,
  "on": true,
  "var": true,
  "const": true,
  "finally": true,
  "operator": true,
  "void": true,
  "continue": true,
  "for": true,
  "part": true,
  "while": true,
  "covarient": true,
  "Function": true,
  "rethrow": true,
  "with": true,
  "default": true,
  "get": true,
  "return": true,
  "yield": true,
  "deffered": true,
  "hide": true,
  "set": true,
  "do": true,
  "if": true,
  "show": true,
  "dynamic": true,
  "implements": true,
  "static": true,
};
